### ISSUE TITLE
I get the error: ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by edunofe** [gilzamir18/AI4U#18]
I get the error 'unsuported pickle protocol: 5' running ai4u with Unity 2021.3.16f1 on Windows 11 with Python 3.7. I install all dependencies. Full stack trace exceptions:

```
PS C:\Users\edu\experimento6\experimento6\controllers\controller1> python .\appgym_sb3test.py
C:\Users\edu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gym\spaces\box.py:74: UserWarning: WARN: Box bound precision lowered by casting to float32
  "Box bound precision lowered by casting to {}".format(self.dtype)
ai4u2unity started...
Agent configuration: id= 1  maxstep= 0
Begin of the episode....
Begin of the episode....
Traceback (most recent call last):
  File ".\appgym_sb3test.py", line 11, in <module>
    model = SAC.load("logs/rl_model_3000000_steps")
  File "C:\Users\edu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\stable_baselines3\common\base_class.py", line 663, in load
    print_system_info=print_system_info,
  File "C:\Users\edu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\stable_baselines3\common\save_util.py", line 421, in load_from_zip_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "C:\Users\edu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\stable_baselines3\common\save_util.py", line 164, in json_to_data
    deserialized_object = cloudpickle.loads(base64_object)
ValueError: unsupported pickle protocol: 5
```

**Comment by gilzamir18** [comment]
It's a documentation problem because error occurred in third part component. This problem can be fixed by upgrade from your current python version to python version (python 3.10 or upper) supporting pickle 5 protocol. Other solution is install pickle5 package:

```
pip install pickle5
```
.
